<?php
namespace cds\Model;

abstract class MemberSearchResultCode
{

    const ADD_NEW_MEMBER = "ADD_NEW_MEMBER";

    const MATCH_BY_NUMBER = "1_MATCH_BY_NUMBER";

    const MATCH_BY_FIRSTNAME = "4_MATCH_BY_FIRSTNAME";

    const MATCH_BY_LASTNAME = "3_MATCH_BY_LASTNAME";

    const MATCH_BY_FIRSTNAME_AND_LASTNAME = "2_MATCH_BY_FIRSTNAME_AND_LASTNAME";

    const SUBSCRIPTION_WITH_OTHER_MEMBER_DATA_EXISTS = "SUBSCRIPTION_WITH_OTHER_MEMBER_DATA_EXISTS";
}

?>