<?php

namespace cds\Model;

use MyCLabs\Enum\Enum;

class SuspectResolvingResultCode extends Enum
{
    // Standard Case
    const SUBSCRIPTION_ADDED = "SUBSCRIPTION_ADDED";

    // Exceptional Cases
    const MEMBER_NOT_FOUND = "MEMBER_NOT_FOUND";
    const SUSPECT_NOT_FOUND = "SUSPECT_NOT_FOUND";

    // For further processing
    const SUBSCRIPTION_ALREADY_EXISTS = "SUBSCRIPTION_ALREADY_EXISTS";
    const SUBSCRIPTION_WITH_OTHER_EMAIL_EXISTS = "SUBSCRIPTION_WITH_OTHER_EMAIL_EXISTS";
    const SUBSCRIPTION_WITH_OTHER_MEMBER_DATA_EXISTS = "SUBSCRIPTION_WITH_OTHER_MEMBER_DATA_EXISTS";
    const SUBSCRIPTION_NOT_EXISTENT = "SUBSCRIPTION_NOT_EXISTENT";

    const SUSPECT_REJECTED_SUCCESSFULLY = "SUSPECT_REJECTED_SUCCESSFULLY";

    const TECHNICAL_ERROR = "TECHNICAL_ERROR";
}